#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# https://github.com/vicfryzel/xmonad-config

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
xmodmap ~/.xmodmap
setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Set a wallpaper
feh --bg-fill ~/.wallpaper.jpg &

# Start the system tray
trayer --edge top --align right --SetDockType true \
 --SetPartialStrut true --width 276 --widthtype pixel --height 23 \
 --transparent true --tint 0x000000 --monitor 1 &
#stalonetray -c ~/.xmonad/stalonetrayrc-dual &

# Start two terminals
konsole &

# start nm-applet
nm-applet &
# Start a browser
chromium-browser &

# Start screensaver
killall gnome-screensaver &
xscreensaver -no-splash &

# Start Franz for communication
franz &

# start a clipping manager
qlipper &

# Start sound server
pulseaudio --start --log-target=syslog &

exec xmonad
